"use strict";
let ARRAY = ["Fatima", "Ali", "Abbas", "Haider"];
let message1 = "hello!";
let message2 = "hey:)";
let message3 = "hi!";
let message4 = "bye:D";
console.log(ARRAY[0], message1);
console.log(ARRAY[1], message2);
console.log(ARRAY[2], message3);
console.log(ARRAY[3], message4);
