var transport = ["motorcycle", "car", "bicycle", "scooter", "bus"];
var messageA = "I would like to own a Honda motorcycle.";
var messageB = "I dream of owning a fancy car.";
var messageC = "Riding a bicycle is so refreshing.";
var messageD = "Scooters are a fun way to zip around.";
var messageE = "Taking the bus is a reliable way to commute.";
console.log(transport[0], messageA);
console.log(transport[1], messageB);
console.log(transport[2], messageC);
console.log(transport[3], messageD);
console.log(transport[4], messageE);
