var animal = 'cat';
var fruit = 'apple';
var temperature = 28;
var time = 14;
var colors = ['red', 'green', 'blue'];
var month = 'July';
console.log(animal == 'dog');
console.log(fruit == 'banana');
console.log(temperature >= 25);
console.log(time < 12);
console.log(colors.includes('green'));
console.log(!colors.includes('yellow'));
console.log(fruit.toLowerCase() === 'apple');
console.log(month.toLowerCase() === 'june');
console.log(temperature !== 30);
console.log(time > 10 && time < 20);
console.log(temperature >= 30 || time > 15);
console.log(colors.includes('purple') && temperature < 20);
console.log(colors.includes('red') || month === 'August');
